# Generated by Django 3.2.3 on 2021-05-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField()),
                ('movie_name', models.CharField(max_length=150, unique=True)),
                ('poster', models.URLField()),
                ('year', models.IntegerField()),
                ('streamOn', models.CharField(max_length=100)),
            ],
        ),
    ]
